# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 492393cccc19af7070589797a7a4bbb6f9f36d6ffe54895dd7a6e06c0f21c1a36c97be9f86a14f33d47b226a79f30d25d1524df3ebd63f421e2b73a89c9e457c

test:
  secret_key_base: 22d2166e1692b582d84086d2e92a9ab602640ddfd97fa808e4b816cfb26e4934d8cbb1a4cf300e9f5ac5e7797330557cb925dc934279679422807644c9fbaa60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
